### ISSUE TITLE
What is the "app path" that needs to be updated? 

### ISSUE THREAD

**Issue by ghost** [batra-mlp-lab/visdial-amt-chat#6]
> Update app path (from vhost) in index.html line 276

Sorry, but I am a little unsure what the "app path" is that needs to be updated. Is simply `http://localhost/socket.io/'`sufficient? 

I ask this because I am getting the following trace back:

```
Error: listen EADDRINUSE :::5000
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1259:14)
    at listen (net.js:1295:10)
    at Server.listen (net.js:1391:5)
    at Object.<anonymous> (/Users/josharnold/Desktop/visdial-amt-chat-master/nodejs/index.js:428:6)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

Thank you for your time,
Josh

**Comment by abhshkdz** [comment]
If your nginx setup looks like the following,
```
location /app1 {
  proxy_pass http://127.0.0.1:5000;
}
```
then line 276 should be
`socket = io.connect(host,{path: '/app1/socket.io/', transports: ["websocket"]});`

You might have to change the port on line 428 as well if 5000 is already being used (and in the nginx config as well to reflect the same).

**Comment by ghost** [comment]
Everything seems to be working by doing what you said previously with your nginx setup, my following nginx config now looks like this:

```
worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;

    # Configure server 
    server {
        listen 5000;
        location /app1 {
             proxy_pass http://127.0.0.1:5000;
        }  
    }

}
```

Does this look correct or am I missing something?

**Comment by abhshkdz** [comment]
Nginx and the reverse proxy can't listen on the same port. I'd suggest:
```
server {
    listen 80;
    location /app1 {
         proxy_pass http://127.0.0.1:5000;
    }  
}
```
